### ISSUE TITLE
Support for Latest SDK version (should be in TiIntercom)

### ISSUE THREAD

**Issue by markive** [simonrand/gitthello#2]
This module looks very promising, there is a new SDK version out which has real-time chat support for example. Is there any plans to wrap the new version?

**Comment by simonrand** [comment]
Not sure I follow? Might you be referring to the TiIntercom repo?

**Comment by markive** [comment]
Whoops, how did I get over here.. Yes apologies I did mean that..  I think I clicked on your username.. ;)

**Comment by simonrand** [comment]
No worries – to answer your question – we/I've no need for the TiIntercom module anymore so it's unlikely I'll update to use the v2 SDK, feel free to fork and PR!
